### ISSUE TITLE
能不能在网页背景图里面加上栋栋彩虹伞的照片？

### ISSUE THREAD

**Issue by LuChang-CS** [derekeeeeely/dz-music#2]

**Comment by derekeeeeely** [comment]
不要搞事情...

**Comment by LuChang-CS** [comment]
Could you please add the rainbow umbrella photo of derekzhou as the background of the website?

We all expect this!!!

**Comment by derekeeeeely** [comment]
no way!!!

**Comment by LuChang-CS** [comment]
你把我的图搞哪儿去了？

**Comment by derekeeeeely** [comment]
我是owner，可以删掉呀

**Comment by LuChang-CS** [comment]
腊鸡<a href="https://user-images.githubusercontent.com/8665565/35051314-ebc29204-fbdf-11e7-8404-a30a35e018d3.jpg" target="_blank">　　　　　　　　　　　　　　　　　　　　　　　　　　　　</a>

**Comment by derekeeeeely** [comment]
excuse me?

**Comment by LuChang-CS** [comment]
lol你是如何发现的哈哈哈哈

**Comment by derekeeeeely** [comment]
毕竟路神的风格

**Comment by LuChang-CS** [comment]
辣鸡
